name: has_field_values
display_name: Has Field Values
description: null
created_at: '2023-10-31T21:26:32.933732Z'
active: true
visibility_type: normal
table_id:
- Internal Metabase Database
- public
- v_fields
database_type: text
base_type: type/Text
effective_type: type/Text
semantic_type: null
database_is_auto_increment: false
database_required: false
fk_target_field_id: null
dimensions: []
json_unfolding: false
parent_id: null
coercion_strategy: null
preview_display: true
position: 10
custom_position: 0
database_position: 10
has_field_values: auto-list
settings: null
caveats: null
points_of_interest: null
nfc_path: null
serdes/meta:
- id: Internal Metabase Database
  model: Database
- id: public
  model: Schema
- id: v_fields
  model: Table
- id: has_field_values
  model: Field
database_indexed: null
database_partitioned: null
