description: null
database_type: text
semantic_type: null
table_id:
- Audit Database
- public
- metabase_fieldvalues
coercion_strategy: null
name: values
fingerprint_version: 0
has_field_values: null
settings: null
caveats: null
fk_target_field_id: null
dimensions: []
custom_position: 0
effective_type: type/Text
active: true
nfc_path: null
parent_id: null
last_analyzed: null
serdes/meta:
- model: Database
  id: Audit Database
- model: Schema
  id: public
- model: Table
  id: metabase_fieldvalues
- model: Field
  id: values
database_is_auto_increment: false
json_unfolding: false
position: 3
visibility_type: normal
preview_display: true
display_name: Values
database_position: 3
database_required: false
fingerprint: null
created_at: '2023-06-02T21:32:53.808251Z'
base_type: type/Text
points_of_interest: null
