[install]
# Increase timeout for large packages (in milliseconds)
timeout = 600000

# Only install package versions published at least 3 days ago
minimumReleaseAge = 259200

# Add packages if versions newer than 3 days are required (e.g. security patch)
# minimumReleaseAgeExcludes = []
