created_at: '2024-08-28T14:38:42.774331Z'
has_more_values: false
hash_key: null
human_readable_values: []
last_used_at: '2024-08-28T14:38:42.774331Z'
type: full
values:
- 02ad6b15-54b0-4491-bf0f-d781b0a2c4f5
- 10a0fea8-9bb4-48fe-a336-4d9cbbd78aa0
- 4be68cda-6fd5-4ba7-944e-2b475600bda5
- 5bb19ad9-f3f8-421f-9750-7d398e38428d
- 62b9602c-27b8-44ea-adbd-2748f26537af
- 75a1ebf1-cae7-4a50-8743-32d97500f2cf
- 900335ad-e03b-4259-abc7-76aac21cedca
- a329ccfe-b99c-42eb-9c93-cb9adc3eb1ab
- a61f97c6-4484-4a63-b37e-b5e58bfa2ecb
- b085040c-7aa4-4e96-8c8f-420b2c99c920
- b7a43e91-9fb9-4fe9-ab6f-ea51ab0f94e4
- d35c9d78-f9cf-4f52-b1cc-cb9078eebdcb
- d6c47a54-9d88-4c4a-8054-ace76764ed0d
- dfe21df3-f364-479d-a5e7-04bc5d85ad2b
- f9b65c74-9f91-4cfd-9248-94a53af82866
serdes/meta:
- id: test-data (h2)
  model: Database
- id: PUBLIC
  model: Schema
- id: USERS
  model: Table
- id: PASSWORD
  model: Field
- id: '0'
  model: FieldValues
