created_at: '2024-08-28T14:38:42.774331Z'
has_more_values: false
hash_key: null
human_readable_values: []
last_used_at: '2024-08-28T14:38:42.774331Z'
type: full
values:
- African
- American
- Artisan
- Asian
- BBQ
- Bakery
- Bar
- Beer Garden
- Breakfast / Brunch
- Brewery
- Burger
- Café
- Café Sweets
- Caribbean
- Chinese
- Coffee Shop
- Comedy Club
- Deli
- Dim Sum
- Diner
- Donut Shop
- English
- Entertainment
- Fashion
- Fast Food
- Food Truck
- French
- Gay Bar
- German
- Gluten-free
- Greek
- Grocery
- Health & Beauty
- Home
- Hostel
- Hot Dog
- Hotel
- Indian
- Italian
- Japanese
- Jewish
- Juice Bar
- Karaoke
- Korean
- Landmark
- Late Dining
- Latin American
- Lounge
- Mediterannian
- Mexican
- Middle Eastern
- Molecular Gastronomy
- Moroccan
- Museum
- Nightclub
- Nightlife
- Outdoors
- Pizza
- Ramen
- Restaurant General
- Scandinavian
- Seafood
- South Pacific
- Southern
- Spanish
- Stadium
- Steakhouse
- Strip Club
- Tapas
- Tea Room
- Thai
- Unknown
- Vegetarian / Vegan
- Wine Bar
- Winery
serdes/meta:
- id: test-data (h2)
  model: Database
- id: PUBLIC
  model: Schema
- id: CATEGORIES
  model: Table
- id: NAME
  model: Field
- id: '0'
  model: FieldValues
