name: Total time looking for field values per day
description: null
entity_id: LN9YtKcxZk_kybyRjJx1J
created_at: '2023-11-13T20:45:10.662006Z'
creator_id: internal@metabase.com
display: line
archived: false
collection_id: vG58R8k-QddHWA7_47umn
collection_preview: true
collection_position: null
query_type: query
database_id: Internal Metabase Database
table_id:
- Internal Metabase Database
- public
- v_tasks
enable_embedding: false
embedding_params: null
made_public_by_id: null
public_uuid: null
parameters: []
parameter_mappings: []
dataset_query:
  database: Internal Metabase Database
  query:
    aggregation:
    - - sum
      - - field
        - - Internal Metabase Database
          - public
          - v_tasks
          - duration_seconds
        - base-type: type/Float
    breakout:
    - - field
      - - Internal Metabase Database
        - public
        - v_tasks
        - started_at
      - base-type: type/DateTimeWithLocalTZ
        temporal-unit: day
    - - field
      - - Internal Metabase Database
        - public
        - v_databases
        - name
      - base-type: type/Text
        join-alias: Databases - Database Qualified
    filter:
    - and
    - - =
      - - field
        - - Internal Metabase Database
          - public
          - v_tasks
          - task
        - base-type: type/Text
      - field values scanning
      - update-field-values
    - - time-interval
      - - field
        - started_at
        - base-type: type/DateTimeWithLocalTZ
      - -14
      - day
      - include-current: true
    joins:
    - alias: Databases - Database Qualified
      condition:
      - =
      - - field
        - - Internal Metabase Database
          - public
          - v_tasks
          - database_qualified_id
        - base-type: type/Text
      - - field
        - - Internal Metabase Database
          - public
          - v_databases
          - entity_qualified_id
        - base-type: type/Text
          join-alias: Databases - Database Qualified
      fields: all
      ident: join_LN9YtKcxZk_kybyRjJx1J@0__Databases - Database Qualified
      source-table: -19557ZnrWiDgG4h4cKxF
      strategy: left-join
    source-table: PKhlEfegdbTozSMfj0aLB
  type: query
result_metadata:
- active: true
  base_type: type/DateTimeWithLocalTZ
  coercion_strategy: null
  database_type: timestamptz
  description: null
  display_name: 'Started At: Day'
  effective_type: type/DateTimeWithLocalTZ
  field_ref:
  - field
  - - Internal Metabase Database
    - public
    - v_tasks
    - started_at
  - base-type: type/DateTimeWithLocalTZ
    temporal-unit: day
  fk_target_field_id: null
  id:
  - Internal Metabase Database
  - public
  - v_tasks
  - started_at
  ident: fDxH2yqCHnftKx3IkW8ra
  name: started_at
  nfc_path: null
  parent_id: null
  position: 4
  semantic_type: type/CreationTimestamp
  settings: null
  source: breakout
  table_id:
  - Internal Metabase Database
  - public
  - v_tasks
  unit: day
  visibility_type: normal
- active: true
  base_type: type/Text
  coercion_strategy: null
  database_type: varchar
  description: null
  display_name: Database Qualified â†’ Name
  effective_type: type/Text
  field_ref:
  - field
  - - Internal Metabase Database
    - public
    - v_databases
    - name
  - base-type: type/Text
    join-alias: Databases - Database Qualified
  fk_field_id: 1583
  fk_target_field_id: null
  id:
  - Internal Metabase Database
  - public
  - v_databases
  - name
  ident: LMqtaUMyPJJMZqYYeSRbs
  name: name
  nfc_path: null
  parent_id: null
  position: 4
  semantic_type: type/Name
  settings: null
  source: breakout
  table_id:
  - Internal Metabase Database
  - public
  - v_databases
  visibility_type: normal
- base_type: type/Float
  display_name: Sum of Duration Seconds
  effective_type: type/Float
  field_ref:
  - aggregation
  - 0
  ident: aggregation_LN9YtKcxZk_kybyRjJx1J@0__0
  name: sum
  semantic_type: type/Quantity
  settings: null
  source: aggregation
visualization_settings:
  column_settings: null
  graph.dimensions:
  - started_at
  - name
  graph.metrics:
  - sum
  graph.series_order: null
  graph.series_order_dimension: null
serdes/meta:
- id: LN9YtKcxZk_kybyRjJx1J
  label: total_time_looking_for_field_values_per_day
  model: Card
archived_directly: false
card_schema: 20
dashboard_id: Glqmoytsnu0n6rfLUjock
metabase_version: vUNKNOWN (a98530f)
source_card_id: PKhlEfegdbTozSMfj0aLB
type: question
