description: Whether we have FieldValues ("list"), should ad-hoc search ("search"), disable entirely ("none"), or infer dynamically (null)"
database_type: text
semantic_type: null
table_id:
- Audit Database
- public
- metabase_field
coercion_strategy: null
name: has_field_values
fingerprint_version: 0
has_field_values: null
settings: null
caveats: null
fk_target_field_id: null
dimensions: []
custom_position: 0
effective_type: type/Text
active: true
nfc_path: null
parent_id: null
last_analyzed: null
serdes/meta:
- model: Database
  id: Audit Database
- model: Schema
  id: public
- model: Table
  id: metabase_field
- model: Field
  id: has_field_values
database_is_auto_increment: false
json_unfolding: false
position: 21
visibility_type: normal
preview_display: true
display_name: Has Field Values
database_position: 21
database_required: false
fingerprint: null
created_at: '2023-06-02T21:32:53.698249Z'
base_type: type/Text
points_of_interest: null
