version: 1
config:
  users:
    - first_name: Crowberto
      last_name: C
      email: crowberto@metabase.com
      password: blackjet
      is_superuser: true
    - first_name: Rasta
      last_name: R
      email: rasta@metabase.com
      password: blueberries
      is_superuser: false
  api-keys:
    - name: "Admin API key"
      group: admin
      creator: crowberto@metabase.com
      key: mb_theadminapikey
    - name: "All Users API key"
      group: all-users
      creator: crowberto@metabase.com
      key: mb_theallusersapikey
