name: Build scripts

on:
  push:
    branches:
      - 'master'
      - 'release-**'
  pull_request:

jobs:

  test-build-scripts:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Prepare back-end environment
      timeout-minutes: 5
      uses: ./.github/actions/prepare-backend
      with:
        m2-cache-key: 'build-scripts'

    - name: Run metabuild-common build script tests
      run: clojure -M:test
      working-directory: bin/common
      timeout-minutes: 15
    - name: Run build-drivers build script tests
      run: clojure -M:test
      working-directory: bin/build-drivers
      timeout-minutes: 15
    - name: Run i18n script tests
      run: clojure -M:test
      working-directory: bin/i18n
      timeout-minutes: 15
    - name: Run build-mb build script tests
      run: clojure -M:test
      working-directory: bin/build-mb
      timeout-minutes: 15
    - name: Run release script tests
      run: clojure -M:test
      working-directory: bin/release
      timeout-minutes: 15
    - name: Run Liquibase migrations linter tests
      run: clojure -M:test
      working-directory: bin/lint-migrations-file
      timeout-minutes: 15
