name: Frontend Test Coverage

on:
  workflow_dispatch:
  schedule:
    - cron: '40 1 * * *' # every day at 1:40

jobs:
  fe-test-coverage:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend
      - name: Run frontend unit tests
        run: |
          bun run test-unit \
            --silent \
            --coverage \
            --testTimeout=60000
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          flags: front-end
          token: ${{ secrets.CODECOV_TOKEN }}
