name: Embedding SDK Component Tests

on:
  workflow_call:

env:
  DISPLAY: "" # https://github.com/cypress-io/cypress/issues/4034
  TERM: xterm
  TZ: US/Pacific # to make Node match the instance tz
  MB_EDITION: "ee"

jobs:
  sdk-component-tests:
    name: "SDK component tests (React ${{ matrix.react-version }})"
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    strategy:
      matrix:
        react-version: [18, 19]
      fail-fast: false
    env:
      # Any env starting with `CYPRESS_` will be available to all Cypress tests via `Cypress.env()`
      # Example: you can get `CYPRESS_FOO` with `Cypress.env("FOO")`
      CYPRESS_MB_ALL_FEATURES_TOKEN: ${{ secrets.STAGING_MB_ALL_FEATURES_TOKEN }}
      CYPRESS_MB_STARTER_CLOUD_TOKEN: ${{ secrets.STAGING_MB_STARTER_CLOUD_TOKEN }}
      CYPRESS_MB_PRO_CLOUD_TOKEN: ${{ secrets.STAGING_MB_PRO_CLOUD_TOKEN }}
      CYPRESS_MB_PRO_SELF_HOSTED_TOKEN: ${{ secrets.STAGING_MB_PRO_SELF_HOSTED_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Prepare Docker containers
        uses: ./.github/actions/e2e-prepare-containers
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          maildev: true
          openldap: false
          webhook: false
          snowplow: false
          postgres: false
          mysql: false
          mongo: false

      - name: Retrieve uberjar artifact for ee
        uses: ./.github/actions/fetch-artifact
        with:
          commit: ${{ github.event.pull_request.head.sha || github.sha }}
          edition: ee
          extract-path: "target/uberjar"
          output-name: "metabase.jar"

      - name: Retrieve Embedding SDK dist artifact
        uses: actions/download-artifact@v4
        with:
          name: embedding-sdk-${{ github.event.pull_request.head.sha || github.sha }}
          path: ${{ github.workspace }}/resources/embedding-sdk

      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend

      - name: Prepare Cypress environment
        id: cypress-prep
        uses: ./.github/actions/prepare-cypress

      - name: Run Metabase
        run: node e2e/runner/run_cypress_ci.js start

      - name: Make app db snapshot
        env:
          CYPRESS_BROWSER: ${{ steps.cypress-prep.outputs.chrome-path }}
        # Component tests only need the default snapshot
        run: |
          node e2e/runner/run_cypress_ci.js snapshot \
            --spec "e2e/snapshot-creators/default.cy.snap.js"

      # Has to be run after the app db snapshot is made, as it is not compatible with React 19
      - name: Change React version to ${{ matrix.react-version }}
        run: ./bin/embedding-sdk/change-react-version.bash ${{ matrix.react-version }}

      - name: Run component tests for Embedding SDK
        id: run-tests
        env:
          CYPRESS_BROWSER: ${{ steps.cypress-prep.outputs.chrome-path }}
        run: node e2e/runner/run_cypress_ci.js component

      - name: Upload Test Results
        uses: ./.github/actions/upload-test-results
        if: always()
        with:
          input-path: ./target/junit
          output-name: e2e-embedding-sdk-react-${{ matrix.react-version }}
          bucket: ${{ vars.AWS_S3_TEST_RESULTS_BUCKET }}
          aws-access-key-id: ${{ secrets.AWS_TEST_RESULTS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TEST_RESULTS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          trunk-api-token: ${{ secrets.TRUNK_API_TOKEN }}
          previous-step-outcome: ${{ steps.run-tests.outcome }}

      - name: "SDK component tests > Upload Cypress Artifacts upon failure"
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-recording-embedding-sdk-react-${{ matrix.react-version }}
          path: |
            ./cypress
            ./logs/test.log
          if-no-files-found: ignore

      - name: "SDK component tests > Publish Summary"
        if: failure()
        uses: actions/github-script@v7
        with:
          script: | #js
            const {
               generateReport,
               parseReport,
               formatSummary
             } = require("./.github/scripts/handle-mochawesome-report.js");

             const report = await generateReport();
             const results = parseReport(report);
             const summary = formatSummary(results);

             await core.summary.addRaw(summary).write();

  decide-target-ref:
    runs-on: ubuntu-latest
    outputs:
      target-ref: ${{ steps.get-target-ref.outputs.value }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Decide ref to checkout
        id: get-target-ref
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "value=${{ github.base_ref }}" >> "$GITHUB_OUTPUT"
          else
            echo "value=$(git rev-parse HEAD^1)" >> "$GITHUB_OUTPUT"
          fi

  # This job ensures that the Embedding SDK package from the current commit (N) works with the
  # Embedding SDK Bundle (Metabase JAR) from the previous commit (N-1).
  # N - 1 is a target of a pull request, or a literal previous commit when this job is run on push in a branch.
  sdk-component-tests-backward-compatibility:
    name: "SDK component tests (Backward compatibility)"
    needs: [decide-target-ref]
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    env:
      MB_RUN_MODE: "e2e"
      METASTORE_DEV_SERVER_URL: ${{ secrets.METASTORE_DEV_SERVER_URL }}
      # Any env starting with `CYPRESS_` will be available to all Cypress tests via `Cypress.env()`
      # Example: you can get `CYPRESS_FOO` with `Cypress.env("FOO")`
      CYPRESS_MB_ALL_FEATURES_TOKEN: ${{ secrets.STAGING_MB_ALL_FEATURES_TOKEN }}
      CYPRESS_MB_STARTER_CLOUD_TOKEN: ${{ secrets.STAGING_MB_STARTER_CLOUD_TOKEN }}
      CYPRESS_MB_PRO_CLOUD_TOKEN: ${{ secrets.STAGING_MB_PRO_CLOUD_TOKEN }}
      CYPRESS_MB_PRO_SELF_HOSTED_TOKEN: ${{ secrets.STAGING_MB_PRO_SELF_HOSTED_TOKEN }}

    steps:
      - name: Check out the code from the previous commit
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.decide-target-ref.outputs.target-ref }}

      - name: Prepare Docker containers
        uses: ./.github/actions/e2e-prepare-containers
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          maildev: true
          openldap: false
          webhook: false
          snowplow: false
          postgres: false
          mysql: false
          mongo: false

      - name: Get the actual commit SHA from the checked out branch
        id: get-commit-sha
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend

      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend

      - name: Attempt to retrieve the ee uberjar artifact from the previous commit
        id: download-uberjar
        uses: ./.github/actions/fetch-artifact
        with:
          commit: ${{ steps.get-commit-sha.outputs.sha }}
          edition: ee
          extract-path: "target/uberjar"
          output-name: "metabase.jar"
        continue-on-error: true # do not break the whole job if this step doesn't succeed

      # Build the uberjar from the previous commit only if we couldn't fetch it.
      # `step.foo.OUTCOME` is important because it looks at the step status *before* continue-on-error is applied.
      # Do not confuse it with the `step.foo.conclusion`.
      - name: Build MB uberjar from the commit N-1
        if: steps.download-uberjar.outcome != 'success'
        run: ./bin/build.sh

      - name: Retrieve Embedding SDK dist artifact built from the current commit N
        uses: actions/download-artifact@v4
        with:
          name: embedding-sdk-${{ github.event.pull_request.head.sha || github.sha }}
          path: ${{ github.workspace }}/resources/embedding-sdk

      - name: Prepare Cypress environment
        id: cypress-prep
        uses: ./.github/actions/prepare-cypress

      - name: Run Metabase
        run: node e2e/runner/run_cypress_ci.js start

      - name: Make app db snapshot
        env:
          CYPRESS_BROWSER: ${{ steps.cypress-prep.outputs.chrome-path }}
        # Component tests only need the default snapshot
        run: |
          node e2e/runner/run_cypress_ci.js snapshot \
            --spec "e2e/snapshot-creators/default.cy.snap.js"

      - name: Run component tests for Embedding SDK
        id: run-tests
        env:
          CYPRESS_BROWSER: ${{ steps.cypress-prep.outputs.chrome-path }}
        run: |
          node e2e/runner/run_cypress_ci.js component \
            --env grepTags="-@skip-backward-compatibility"

      - name: Upload Test Results
        uses: ./.github/actions/upload-test-results
        if: always()
        with:
          input-path: ./target/junit
          output-name: e2e-embedding-sdk
          bucket: ${{ vars.AWS_S3_TEST_RESULTS_BUCKET }}
          aws-access-key-id: ${{ secrets.AWS_TEST_RESULTS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TEST_RESULTS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          trunk-api-token: ${{ secrets.TRUNK_API_TOKEN }}
          previous-step-outcome: ${{ steps.run-tests.outcome }}

      - name: Upload Cypress Artifacts upon failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-recording-embedding-sdk-cross-version
          path: |
            ./cypress
            ./logs/test.log
          if-no-files-found: ignore

      - name: Publish Summary
        if: failure()
        uses: actions/github-script@v7
        with:
          script: | #js
            const {
               generateReport,
               parseReport,
               formatSummary
             } = require("./.github/scripts/handle-mochawesome-report.js");

             const report = await generateReport();
             const results = parseReport(report);
             const summary = formatSummary(results);

             await core.summary.addRaw(summary).write();
