name: Embedding SDK Component Tests

on:
  workflow_call:
    inputs:
      cached-embedding-sdk-dist-artifact-name:
        required: true
        type: string

jobs:
  sdk-component-tests:
    name: "SDK component tests (React ${{ matrix.react-version }})"
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    strategy:
      matrix:
        react-version: [18, 19]
      fail-fast: false
    env:
      MB_EDITION: ee
      DISPLAY: ""
      MB_RUN_MODE: "e2e"
      METASTORE_DEV_SERVER_URL: ${{ secrets.METASTORE_DEV_SERVER_URL }}
      # Any env starting with `CYPRESS_` will be available to all Cypress tests via `Cypress.env()`
      # Example: you can get `CYPRESS_FOO` with `Cypress.env("FOO")`
      CYPRESS_MB_ALL_FEATURES_TOKEN: ${{ secrets.STAGING_MB_ALL_FEATURES_TOKEN }}
      CYPRESS_MB_STARTER_CLOUD_TOKEN: ${{ secrets.STAGING_MB_STARTER_CLOUD_TOKEN }}
      CYPRESS_MB_PRO_CLOUD_TOKEN: ${{ secrets.STAGING_MB_PRO_CLOUD_TOKEN }}
      CYPRESS_MB_PRO_SELF_HOSTED_TOKEN: ${{ secrets.STAGING_MB_PRO_SELF_HOSTED_TOKEN }}
      COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title || github.event.head_commit.message || github.event.head.sha }}
      TZ: US/Pacific # to make node match the instance tz
      CYPRESS_CI: true

    steps:
      - uses: actions/checkout@v4

      - name: Retrieve uberjar artifact for ee
        uses: actions/download-artifact@v4
        with:
          name: metabase-ee-${{ github.event.pull_request.head.sha || github.sha }}-uberjar

      - name: Retrieve Embedding SDK dist artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.cached-embedding-sdk-dist-artifact-name }}
          path: ${{ github.workspace }}/resources/embedding-sdk

      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend

      - name: Prepare JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - name: Prepare Cypress environment
        id: cypress-prep
        uses: ./.github/actions/prepare-cypress

      - name: Run Metabase
        run: node e2e/runner/run_cypress_ci.js start

      - name: Make app db snapshot
        env:
          CYPRESS_BROWSER: ${{ steps.cypress-prep.outputs.chrome-path }}
        run: node e2e/runner/run_cypress_ci.js snapshot

      # Has to be run after the app db snapshot is made, as it is not compatible with React 19
      - name: Change React version to ${{ matrix.react-version }}
        run: ./bin/embedding-sdk/change-react-version.bash ${{ matrix.react-version }}

      - name: Run component tests for Embedding SDK
        env:
          CYPRESS_BROWSER: ${{ steps.cypress-prep.outputs.chrome-path }}
        run: node e2e/runner/run_cypress_ci.js component

      - name: Upload Test Results
        uses: ./.github/actions/upload-test-results
        if: always()
        with:
          input-path: ./target/junit
          output-name: e2e-embedding-sdk-react-${{ matrix.react-version }}
          bucket: ${{ vars.AWS_S3_TEST_RESULTS_BUCKET }}
          aws-access-key-id: ${{ secrets.AWS_TEST_RESULTS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TEST_RESULTS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          trunk-api-token: ${{ secrets.TRUNK_API_TOKEN }}

      - name: "SDK component tests > Upload Cypress Artifacts upon failure"
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-recording-embedding-sdk-react-${{ matrix.react-version }}
          path: |
            ./cypress
            ./logs/test.log
          if-no-files-found: ignore

      - name: "SDK component tests > Publish Summary"
        if: failure()
        uses: actions/github-script@v7
        with:
          script: | #js
            const {
               generateReport,
               parseReport,
               formatSummary
             } = require("./.github/scripts/handle-mochawesome-report.js");

             const report = await generateReport();
             const results = parseReport(report);
             const summary = formatSummary(results);

             await core.summary.addRaw(summary).write();
