name: Fuzzing

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "release-**"
    paths:
      - "frontend/src/metabase/querying/expressions/**"
  pull_request:
    paths:
      - "frontend/src/metabase/querying/expressions/**"

jobs:
  fe-fuzz-lexifier:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend
      - run: pnpm test-unit frontend/src/metabase/querying/expressions/pratt/fuzz.lexifier.unit.spec.ts
        env:
          MB_FUZZ: 1
        name: Run fuzz testing on the lexifier

  fe-fuzz-compiler:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend
      - run: pnpm test-unit frontend/src/metabase/querying/expressions/fuzz.compiler.unit.spec.ts
        env:
          MB_FUZZ: 1
        name: Run fuzz testing on the custom expression compiler

  fe-fuzz-string-quoting:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend
      - run: pnpm test-unit frontend/src/metabase/querying/expressions/fuzz.string.unit.spec.ts
        env:
          MB_FUZZ: 1
        name: Run fuzz testing on the custom expression string quoter
