name: i18n

on:
  pull_request:
  push:
    branches:
      - '**'
    paths:
    - '**.clj*'
    - '**.js'
    - '**.jsx'
    - '.github/workflows/**'
    - 'bin/**'

jobs:

  verify-i18n-files:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Get yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-i18n-${{ hashFiles('**/yarn.lock') }}
    - name: Get node_modules cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile --prefer-offline

    - run: sudo apt install gettext

    - name: Install Clojure CLI
      run: |
        curl -O https://download.clojure.org/install/linux-install-1.10.3.933.sh &&
        sudo bash ./linux-install-1.10.3.933.sh
    - name: Get M2 cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.gitlibs
        key: ${{ runner.os }}-i18n-${{ hashFiles('**/deps.edn') }}

    - run: ./bin/i18n/update-translation-template
      name: Check i18n tags/make sure template can be built
    - run: ./bin/i18n/build-translation-resources
      name: Verify i18n translations (.po files)
