name: Mage Tests

on:
  pull_request:
    paths:
      - "mage/**"
      - "bb.edn"

jobs:
  # run mage tests even if the rest of be isnt needed
  mage-tests:
    runs-on: ubuntu-22.04
    name: Mage
    steps:
      - uses: actions/checkout@v4
      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend
      - name: Check mage runs
        run: ./bin/mage -h
      - name: Run mage tests
        run: ./bin/mage -test
