name: Release Code Tests

on:
  push:
    branches:
      - "master"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  files-changed:
    name: Check which files changed
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    outputs:
      release_source: ${{ steps.changes.outputs.release_source }}
    steps:
      - uses: actions/checkout@v4
      - name: Test which files changed
        uses: dorny/paths-filter@v3.0.0
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-paths.yaml

  release-type-check:
    needs: files-changed
    if: needs.files-changed.outputs.release_source == 'true'
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: "release"
      - uses: oven-sh/setup-bun@v2
      - name: prepare dependencies in release directory
        run: bun install --frozen-lockfile --cwd release
      - name: Run frontend type-check
        run: bun --cwd release run type-check

  release-tests-unit:
    needs: files-changed
    if: needs.files-changed.outputs.release_source == 'true'
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: "release"
      - uses: oven-sh/setup-bun@v2
      - name: prepare dependencies in release directory
        run: bun install --frozen-lockfile --cwd release
      - name: Run release unit tests
        run: bun --cwd release run test:unit

  release-test-build:
    needs: files-changed
    if: needs.files-changed.outputs.release_source == 'true'
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: "release"
      - uses: oven-sh/setup-bun@v2
      - name: prepare dependencies in release directory
        run: bun install --frozen-lockfile --cwd release
      - name: Build release bundle
        run: bun --cwd release run build
      - name: Smoke test release bundle
        run: node release/dist/index.cjs
