name: cache_field_values_schedule
display_name: Cache Field Values Schedule
description: null
created_at: '2023-10-31T21:26:33.02415Z'
active: true
visibility_type: normal
table_id:
- Internal Metabase Database
- public
- v_databases
database_type: varchar
base_type: type/Text
effective_type: type/Text
semantic_type: type/Category
database_is_auto_increment: false
database_required: false
fk_target_field_id: null
dimensions: []
json_unfolding: false
parent_id: null
coercion_strategy: null
preview_display: true
position: 8
custom_position: 0
database_position: 8
has_field_values: auto-list
settings: null
caveats: null
points_of_interest: null
nfc_path: null
serdes/meta:
- id: Internal Metabase Database
  model: Database
- id: public
  model: Schema
- id: v_databases
  model: Table
- id: cache_field_values_schedule
  model: Field
database_indexed: null
database_partitioned: null
